# -*- coding: utf-8 -*-
"""CSCI164Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hG9HZCtxDeWD0q5EaytthE3kVD388VIB

# Heart Diease Prediction  

This dataset was used in a kaggle competition around two months ago which will be used as a basline of how will regular simple and quick models such as linear regression and MLP compare to the highly tuned single real MLP
"""

import kagglehub
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, StratifiedKFold  #necessary to train/split the data, GridSearchCV to find the optimal hyperparameters, and kfold to optimize the data
from sklearn.preprocessing import StandardScaler, OneHotEncoder # preprocessing to standarize the features
from sklearn.compose import ColumnTransformer # allows different transformers for the dataset
from sklearn.pipeline import Pipeline # Preprocessing to manage the workflow

from sklearn.linear_model import LogisticRegression # Model for Logistic Regresssion
from sklearn.neural_network import MLPClassifier # Model for Multi layer Perceptron
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, RocCurveDisplay, accuracy_score, precision_score, recall_score, f1_score, roc_curve # Metrics

kagglehub.login()

competition_path = kagglehub.competition_download("playground-series-s6e2") # dowloading the dataset from kaggle
print(os.listdir(competition_path))

train_df = pd.read_csv(os.path.join(competition_path, 'train.csv')) # loading data set in panda data frame
test_df = pd.read_csv(os.path.join(competition_path, 'test.csv'))
sample_sub = pd.read_csv(os.path.join(competition_path, 'sample_submission.csv'))
print(train_df.info())
print(train_df.head())
print(train_df.shape)
print(test_df.shape)

train_df['Heart Disease'].value_counts(normalize=True)

categorical_cols = ['Age', 'BP', 'Cholesterol', 'Max HR', 'ST depression', 'Thallium']
numerical_cols = ['Sex', 'Chest pain type', 'FBS over 120', 'EKG results', 'Exercise angina', 'Slope of ST', 'Number of vessels fluro']
# seperating the features into categorical columns and numerical columns for preprocessing

X = train_df.drop(columns=['Heart Disease', 'id'])
y = train_df['Heart Disease'].map({'Absence': 0, 'Presence': 1}) # Convert target to numerical
X_test = test_df.drop(columns=['id'])

preprocessor = ColumnTransformer([ # Formatting the columns appropriately
    ('num', StandardScaler(), numerical_cols),
    ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_cols)
])

pipeline = Pipeline([ #Applying transformers and etimator for Logisitic Regression
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(random_state=42, max_iter=1000, solver='lbfgs'))
])

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, # splitting the data into training and validaiton sets
                                                  random_state=42, stratify=y)

param_grid = { #defining hyperparameters
    'classifier__C': [0.01, 0.1, 1, 10],
    'classifier__penalty': ['l2'],
    'classifier__solver': ['lbfgs', 'newton-cg']
}

grid = GridSearchCV(pipeline, param_grid, cv=StratifiedKFold(5), #Initialize GridSearch
                    scoring='roc_auc', n_jobs=-1, verbose=1)
grid.fit(X_train, y_train) # Training and looking for the best verion

print("\nBest parameters:", grid.best_params_)
print("Best cross-validation ROC-AUC:", grid.best_score_)

best_model = grid.best_estimator_ #Best performing parameters with logistic regression model
y_pred = best_model.predict(X_val) # class predictions
y_proba = best_model.predict_proba(X_val)[:, 1] # Needed for ROC-AUC to predict positive classes

acc = accuracy_score(y_val, y_pred)
prec = precision_score(y_val, y_pred, pos_label=1)
rec = recall_score(y_val, y_pred, pos_label=1)
f1 = f1_score(y_val, y_pred, pos_label=1)

roc_auc = roc_auc_score(y_val, y_proba)

print("\n=== Validation Performance ===")
print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1-score:  {f1:.4f}")
print(f"ROC-AUC:   {roc_auc:.4f}")

m = confusion_matrix(y_val, y_pred)
plt.figure(figsize=(6,5))
sns.heatmap(m, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - Logistic Regression')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

fpr, tpr, _ = roc_curve(y_val, y_proba)
plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f'Logistic Regression (AUC = {roc_auc:.3f})')
plt.plot([0,1], [0,1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.show()

mlp_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', MLPClassifier(random_state=42, max_iter=1000, early_stopping=True))
])

mlp_param_grid = { #defining hyperparameters for MLP grid
    'classifier__hidden_layer_sizes': [(100,)],
    'classifier__activation': ['relu'],
    'classifier__alpha': [0.001, 0.01],
    'classifier__learning_rate_init': [0.001]
}

mlp_grid_cv = GridSearchCV(mlp_pipeline, mlp_param_grid, cv=StratifiedKFold(2),  #Initialize GridSearch
                                 scoring='roc_auc', n_jobs=-1, verbose=1)
mlp_grid_cv.fit(X_train, y_train) #tuning and looking for the best model

print(f"\nBest parameters : {mlp_grid_cv.best_params_}")
print(f"Best cross-validation ROC-AUC : {mlp_grid_cv.best_score_:.4f}")

mlp_best = mlp_grid_cv.best_estimator_ #Best performing parameters with MLP model
mlp_pred = mlp_grid_cv.predict(X_val)
mlp_proba = mlp_grid_cv.predict_proba(X_val)[:, 1]

mlp_metrics = {
    'Accuracy': accuracy_score(y_val, mlp_pred),
    'Precision': precision_score(y_val, mlp_pred),
    'Recall': recall_score(y_val, mlp_pred),
    'F1-score': f1_score(y_val, mlp_pred),
    'ROC-AUC': roc_auc_score(y_val, mlp_proba)
}

print("\n=== MLP Validation Performance ===")
for metric, value in mlp_metrics.items():
    print(f"{metric}: {value:.4f}")

m = confusion_matrix(y_val, mlp_pred)
plt.figure(figsize=(6,5))
sns.heatmap(m, annot=True, fmt='d', cmap='Greens')
plt.title('Confusion Matrix - Logistic Regression')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

fpr, tpr, _ = roc_curve(y_val, mlp_proba)
plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f'Logistic Regression (AUC = {roc_auc:.3f})')
plt.plot([0,1], [0,1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.show()

lr_metrics = {
    'Accuracy': accuracy_score(y_val, y_pred),
    'Precision': precision_score(y_val, y_pred),
    'Recall': recall_score(y_val, y_pred),
    'F1-score': f1_score(y_val, y_pred),
    'ROC-AUC': roc_auc_score(y_val, y_proba)
}

comparison_df = pd.DataFrame({
    'Metric': list(lr_metrics.keys()),
    'Logistic Regression': list(lr_metrics.values()),
    'MLP': list(mlp_metrics.values())
})
print(comparison_df.to_string(index=False))

def compute_oof_auc(model_pipeline, X, y, n_splits=5, random_state=42): #implementation to comput OOF AUC
    """
    Compute Out-Of-Fold AUC for a given model pipeline.

    Parameters:
    - model_pipeline: a sklearn Pipeline (or any estimator with .fit and .predict_proba)
    - X: features (DataFrame or array)
    - y: target (Series or array)
    - n_splits: number of folds
    - random_state: for reproducibility

    Returns:
    - oof_auc: float, the ROC‑AUC on OOF predictions
    - oof_probas: array of predicted probabilities for the whole dataset (same order as y)
    """
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    oof_probas = np.zeros(len(y))

    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
        X_train_fold = X.iloc[train_idx]
        X_val_fold = X.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]

        from sklearn.base import clone   # Cloning the pipeline to avoid overwriting parameters

        model_fold = clone(model_pipeline)
        model_fold.fit(X_train_fold, y_train_fold)

        proba_val = model_fold.predict_proba(X_val_fold)[:, 1]
        oof_probas[val_idx] = proba_val

        print(f"Fold {fold+1} done.")

    oof_auc = roc_auc_score(y, oof_probas)
    return oof_auc, oof_probas

best_model = grid.best_params_
final_lr_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(
        C=best_model['classifier__C'],
        solver=best_model['classifier__solver'],
        random_state=42, max_iter=1000
    ))
])

oof_auc_lr, oof_probas_lr = compute_oof_auc(final_lr_pipeline, X, y, n_splits=5)
print(f"Logistic Regression OOF AUC = {oof_auc_lr:.5f}")

mlp_best = mlp_grid_cv.best_params_
final_mlp_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', MLPClassifier(
        hidden_layer_sizes=mlp_best['classifier__hidden_layer_sizes'],
        activation=mlp_best['classifier__activation'],
        alpha=mlp_best['classifier__alpha'],
        learning_rate_init=mlp_best['classifier__learning_rate_init'],
        random_state=42, max_iter=1000, early_stopping=True
    ))
])

oof_auc_mlp, oof_probas_mlp = compute_oof_auc(final_mlp_pipeline, X, y, n_splits=5)
print(f"MLP OOF AUC = {oof_auc_mlp:.5f}")